all:
	g++ -pg -g -o new-delete             new-delete.cc
	g++ -pg -g -o array-new-delete       array-new-delete.cc
	g++ -pg -g -o wrong-array-new-delete wrong-array-new-delete.cc

clean:
	rm -f gmon.out new-delete array-new-delete wrong-array-new-delete
